name: "trigger or nor"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types:
      - released

jobs:
  helloworld:
    runs-on: self-hosted
    steps:
      - run: echo 'hello world'
