name: "Hello world"
on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types:
      - released

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ env.FOO }}'
