name: Go formatting
on:
  push:
    branches: [master]
    paths:
      - '**.go'

jobs:
  go-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3

      - name: Run make format
        run: make format

      - uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          message: 'chore: go formatting'
          default_author: 'github_actions'
          pathspec_error_handling: exitImmediately
