name: Release

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag
        id: semver
        uses: K-Phoen/semver-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    if: ${{ jobs.release.steps.semver.outputs.tag != '' }}
    uses: ./.github/workflows/docker-build.yml
